//MODES
export const MODE_PANNING = 'MODE_PANNING';
export const MODE_ADDING_COMMENT = 'MODE_ADDING_COMMENT';
export const MODE_MODIFYING_COMMENT = 'MODE_MODIFYING_COMMENT_TEXT';
export const MODE_ZOOMING_IN = 'MODE_ZOOMING_IN';
export const MODE_ZOOMING_OUT = 'MODE_ZOOMING_OUT';
export const MODE_FILE_BROWSER = 'MODE_FILE_BROWSER';