//MODES
export const MODE_PANNING = 'MODE_PANNING';
export const MODE_ADDING_COMMENT = 'MODE_ADDING_COMMENT';
export const MODE_ZOMMING_IN = 'MODE_ZOMMING_IN';
export const MODE_ZOMMING_OUT = 'MODE_ZOMMING_OUT';